COMPANY_MAP = {
        "dermatology": {
            "cigna": "DNS Cigna",
            "aetna": "DNS Aetna",
            "oxford": "DNS Oxford",
            "florida blue": "DNS BCBS",
            "humana": "DNS Humana",
            "uhc": "DNS UHC",
        },
        "pain management": {
            "cigna": "PMC Cigna",
            "aetna": "PM Aetna",
            "oxford": "PM Oxford",
            "florida blue": "PM BCBS",
            "humana": "PM Humana",
            "uhc": "PM UHC",
        },
        "podiatry": {
            "cigna": "PNS Cigna",
            "aetna": "PNS Aetna",
            "oxford": "PNS Oxford",
            "florida blue": "PNS BCBS",
            "humana": "PNS Humana",
            "uhc": "PNS UHC",
        },
        "orthopedic": {
            "cigna": "ONS Cigna",
            "aetna": "ONS Aetna",
            "oxford": "ONS Oxford",
            "florida blue": "ONS BCBS",
            "humana": "ONS Humana",
            "uhc": "ONS UHC",
        },
    }

CATEGORY_MAP = {
        "ARNP": "ARNP - ARNP",
        "CRNA": "CRNA - CRNA",
        "CRNP": "CRNP - CRNP",
        "DC": "DC - CHIROPRACTORS",
        "DDS": "DDS - DDS",
        "DO": "DO - OSTEOPATHIC PHYSICIAN",
        "DPM": "DPM - DPM",
        "FNP": "FNP - FAMILY NURSE PRACTITIONER",
        "LM": "LM - LICENCE MIDWIFE",
        "MD": "MD - MD",
        "MID": "MID - MIDWIFE",
        "ND": "ND - NATUROPATHIC DOCTOR",
        "NMW": "NMW - NURSE MIDWIFE",
        "NP": "NP - NURSE PRACITIONER",
        "PA": "PA - PHYSICIAN ASSISTANT",
        "PHD": "PHD - PHD",
        "PT": "PT - PHYSICAL THERAPY",
        "RD": "RD - REGISTERED DIETICIAN",
        "RN": "RN - REGISTERED NURSE",
        "PA-C": "PA - PHYSICIAN ASSISTANT",
    }

STATE_DROPDOWN_MAP = {
        "Alabama": "AL - ALABAMA",
        "Alaska": "AK - ALASKA",
        "Arizona": "AZ - ARIZONA",
        "Arkansas": "AR - ARKANSAS",
        "California": "CA - CALIFORNIA",
        "Colorado": "CO - COLORADO",
        "Connecticut": "CT - CONNECTICUT",
        "Delaware": "DE - DELAWARE",
        "D.C.": "DC - D.C.",
        "Florida": "FL - FLORIDA",
        "Georgia": "GA - GEORGIA",
        "Hawaii": "HI - HAWAII",
        "Idaho": "ID - IDAHO",
        "Illinois": "IL - ILLINOIS",
        "Indiana": "IN - INDIANA",
        "Iowa": "IA - IOWA",
        "Kansas": "KS - KANSAS",
        "Kentucky": "KY - KENTUCKY",
        "Louisiana": "LA - LOUISIANA",
        "Maine": "ME - MAINE",
        "Maryland": "MD - MARYLAND",
        "Massachusetts": "MA - MASSACHUSETTS",
        "Michigan": "MI - MICHIGAN",
        "Minnesota": "MN - MINNESOTA",
        "Mississippi": "MS - MISSISSIPPI",
        "Missouri": "MO - MISSOURI",
        "Montana": "MT - MONTANA",
        "Nebraska": "NE - NEBRASKA",
        "Nevada": "NV - NEVADA",
        "New Hampshire": "NH - NEW HAMPSHIRE",
        "New Jersey": "NJ - NEW JERSEY",
        "New Mexico": "NM - NEW MEXICO",
        "New York": "NY - NEW YORK",
        "North Carolina": "NC - NORTH CAROLINA",
        "North Dakota": "ND - NORTH DAKOTA",
        "Ohio": "OH - OHIO",
        "Oklahoma": "OK - OKLAHOMA",
        "Oregon": "OR - OREGON",
        "Pennsylvania": "PA - PENNSYLVANIA",
        "Puerto Rico": "PR - PUERTO RICO",
        "Rhode Island": "RI - RHODE ISLAND",
        "South Carolina": "SC - SOUTH CAROLINA",
        "South Dakota": "SD - SOUTH DAKOTA",
        "Tennessee": "TN - TENNESSEE",
        "Texas": "TX - TEXAS",
        "Utah": "UT - UTAH",
        "Vermont": "VT - VERMONT",
        "Virginia": "VA - VIRGINIA",
        "Virgin Islands": "VI - VIRGIN ISLANDS",
        "Washington": "WA - WASHINGTON",
        "West Virginia": "WV - WEST VIRGINIA",
        "Wisconsin": "WI - WISCONSIN",
        "Wyoming": "WY - WYOMING",
    }
PRIMARY_SPECIALITY_MAP = {
        "Dermatology": "D - DERMATOLOGY",
        "Podiatry": "POD - PODIATRY",
        "Orthopedic": "ORT - ORTHOPEDICS",
        "Pain Management": "APM - ANESTHESIOLOGY/PAIN MANAGEMENT",
    }