apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

